import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import HeaderLayout from "./components/header";
import FooterLayout from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <HeaderLayout />
        {children}
        <FooterLayout />
      </body>
    </html>
  );
}
